# Dependencies
markdown:         kramdown
kramdown:
  extensions: ["tables"]

highlighter:         true

# Permalinks
permalink:        pretty

# SetupJ
title:            Vincent Wong
tagline:          'Data Science, Blogging'
url:              http://vincetallica.github.io

author:
  name:           'Vincent Wong'
  url:            https://twitter.com/vincetallica

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           github.com/vincetallica/vincetallica.github.io

# This is the list of pages to include in the header of the website.
pages_list:       
  About: '/about/'
  Archive: '/archive/'
  Feed: '/atom.xml'

# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
  - jekyll-paginate
